// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function GetCurrentUserRole():Promise<string>;

export function Login(arg1:string,arg2:string):Promise<model.User>;
