// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCurrentUserRole() {
  return window['go']['api']['AuthAPI']['GetCurrentUserRole']();
}

export function Login(arg1, arg2) {
  return window['go']['api']['AuthAPI']['Login'](arg1, arg2);
}
