// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BackupByCourse(arg1:string,arg2:string):Promise<string>;

export function BackupByTerm(arg1:string):Promise<string>;

export function ListBackups():Promise<Array<string>>;

export function RestoreFromBackup(arg1:string):Promise<void>;
