// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BackupByCourse(arg1, arg2) {
  return window['go']['api']['BackupAPI']['BackupByCourse'](arg1, arg2);
}

export function BackupByTerm(arg1) {
  return window['go']['api']['BackupAPI']['BackupByTerm'](arg1);
}

export function ListBackups() {
  return window['go']['api']['BackupAPI']['ListBackups']();
}

export function RestoreFromBackup(arg1) {
  return window['go']['api']['BackupAPI']['RestoreFromBackup'](arg1);
}
