// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCourse(arg1) {
  return window['go']['api']['CourseAPI']['CreateCourse'](arg1);
}

export function DeleteCourse(arg1) {
  return window['go']['api']['CourseAPI']['DeleteCourse'](arg1);
}

export function GetAllCourses() {
  return window['go']['api']['CourseAPI']['GetAllCourses']();
}

export function SearchCourses(arg1) {
  return window['go']['api']['CourseAPI']['SearchCourses'](arg1);
}
