// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function CreateCourse(arg1:model.Course):Promise<void>;

export function DeleteCourse(arg1:number):Promise<void>;

export function GetAllCourses():Promise<Array<model.Course>>;

export function SearchCourses(arg1:string):Promise<Array<model.Course>>;
