// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportCourseStats(arg1) {
  return window['go']['api']['ExcelAPI']['ExportCourseStats'](arg1);
}

export function ExportStudentStats(arg1) {
  return window['go']['api']['ExcelAPI']['ExportStudentStats'](arg1);
}
