// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportCourseStats(arg1:number):Promise<string>;

export function ExportStudentStats(arg1:number):Promise<string>;
