// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetGpaRules():Promise<string>;

export function RecalculateAllGPA():Promise<number>;

export function ResetGpaRules():Promise<void>;

export function SaveGpaRules(arg1:string):Promise<void>;
