// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetGpaRules() {
  return window['go']['api']['GpaAPI']['GetGpaRules']();
}

export function RecalculateAllGPA() {
  return window['go']['api']['GpaAPI']['RecalculateAllGPA']();
}

export function ResetGpaRules() {
  return window['go']['api']['GpaAPI']['ResetGpaRules']();
}

export function SaveGpaRules(arg1) {
  return window['go']['api']['GpaAPI']['SaveGpaRules'](arg1);
}
