// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AggregateGrades(arg1, arg2) {
  return window['go']['api']['GradeAPI']['AggregateGrades'](arg1, arg2);
}

export function BatchAdjustScores(arg1, arg2, arg3) {
  return window['go']['api']['GradeAPI']['BatchAdjustScores'](arg1, arg2, arg3);
}

export function BatchImportGrades(arg1) {
  return window['go']['api']['GradeAPI']['BatchImportGrades'](arg1);
}

export function CreateGrade(arg1) {
  return window['go']['api']['GradeAPI']['CreateGrade'](arg1);
}

export function DeleteGrade(arg1) {
  return window['go']['api']['GradeAPI']['DeleteGrade'](arg1);
}

export function ExportTranscript(arg1) {
  return window['go']['api']['GradeAPI']['ExportTranscript'](arg1);
}

export function GetAllGrades() {
  return window['go']['api']['GradeAPI']['GetAllGrades']();
}

export function SearchGrades(arg1, arg2, arg3) {
  return window['go']['api']['GradeAPI']['SearchGrades'](arg1, arg2, arg3);
}

export function UpdateGrade(arg1, arg2) {
  return window['go']['api']['GradeAPI']['UpdateGrade'](arg1, arg2);
}
