// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';
import {model} from '../models';

export function AggregateGrades(arg1:string,arg2:string):Promise<Array<service.AggregatedGrade>>;

export function BatchAdjustScores(arg1:number,arg2:number,arg3:number,arg4:number):Promise<service.BatchAdjustResult>;

export function BatchImportGrades(arg1:Array<model.Grade>):Promise<number>;

export function CreateGrade(arg1:model.Grade):Promise<void>;

export function DeleteGrade(arg1:number):Promise<void>;

export function GetAllGrades():Promise<Array<model.Grade>>;

export function SearchGrades(arg1:string,arg2:string,arg3:string):Promise<Array<model.Grade>>;

export function UpdateGrade(arg1:number,arg2:number):Promise<void>;
