// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function GetAllOperationLogs():Promise<Array<model.OperationLog>>;

export function GetOperationLogsByStudent(arg1:string):Promise<Array<model.OperationLog>>;

export function GetOperationLogsByTerm(arg1:string):Promise<Array<model.OperationLog>>;

export function ReadErrorLogs():Promise<Array<model.ErrorLog>>;

export function SearchOperationLogs(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<Array<model.OperationLog>>;
