// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllOperationLogs() {
  return window['go']['api']['LogAPI']['GetAllOperationLogs']();
}

export function GetOperationLogsByStudent(arg1) {
  return window['go']['api']['LogAPI']['GetOperationLogsByStudent'](arg1);
}

export function GetOperationLogsByTerm(arg1) {
  return window['go']['api']['LogAPI']['GetOperationLogsByTerm'](arg1);
}

export function ReadErrorLogs() {
  return window['go']['api']['LogAPI']['ReadErrorLogs']();
}

export function SearchOperationLogs(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['api']['LogAPI']['SearchOperationLogs'](arg1, arg2, arg3, arg4, arg5, arg6);
}
