// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function GenerateStatisticsReport(arg1:string):Promise<string>;

export function GetCourseStatistics(arg1:number):Promise<model.CourseStatistics>;

export function GetStudentRanking():Promise<Array<model.StudentRanking>>;

export function GetStudentStatistics():Promise<Array<model.StudentStatistics>>;
