// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateStatisticsReport(arg1) {
  return window['go']['api']['StatisticsAPI']['GenerateStatisticsReport'](arg1);
}

export function GetCourseStatistics(arg1) {
  return window['go']['api']['StatisticsAPI']['GetCourseStatistics'](arg1);
}

export function GetStudentRanking() {
  return window['go']['api']['StatisticsAPI']['GetStudentRanking']();
}

export function GetStudentStatistics() {
  return window['go']['api']['StatisticsAPI']['GetStudentStatistics']();
}
