// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateStudent(arg1) {
  return window['go']['api']['StudentAPI']['CreateStudent'](arg1);
}

export function DeleteStudent(arg1) {
  return window['go']['api']['StudentAPI']['DeleteStudent'](arg1);
}

export function GetAllStudents() {
  return window['go']['api']['StudentAPI']['GetAllStudents']();
}

export function GetStudentsByPage(arg1, arg2) {
  return window['go']['api']['StudentAPI']['GetStudentsByPage'](arg1, arg2);
}

export function SearchStudents(arg1) {
  return window['go']['api']['StudentAPI']['SearchStudents'](arg1);
}
