// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function CreateStudent(arg1:model.Student):Promise<void>;

export function DeleteStudent(arg1:number):Promise<void>;

export function GetAllStudents():Promise<Array<model.Student>>;

export function GetStudentsByPage(arg1:number,arg2:number):Promise<model.StudentPageResult>;

export function SearchStudents(arg1:string):Promise<Array<model.Student>>;
