// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangePassword(arg1, arg2) {
  return window['go']['api']['UserAPI']['ChangePassword'](arg1, arg2);
}

export function CreateTeacher(arg1, arg2) {
  return window['go']['api']['UserAPI']['CreateTeacher'](arg1, arg2);
}

export function DeleteUser(arg1) {
  return window['go']['api']['UserAPI']['DeleteUser'](arg1);
}

export function GetAllTeachers() {
  return window['go']['api']['UserAPI']['GetAllTeachers']();
}
