// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function ChangePassword(arg1:string,arg2:string):Promise<void>;

export function CreateTeacher(arg1:string,arg2:string):Promise<void>;

export function DeleteUser(arg1:string):Promise<void>;

export function GetAllTeachers():Promise<Array<model.User>>;
